// Alle Texte des Spiels. Schweizer Schreibweise: «ss», nie «ß».
// Im HTML tragen Elemente data-t="schlüssel"; main.js setzt beim Start den Text von hier ein.

export const T = {
  brandA: "Netz", brandB: "roller",
  lede: "Tennis für zwei Handys. Beide sehen den ganzen Platz, jedes Handy steuert den eigenen Schläger.",
  nameLabel: "Dein Name", namePlaceholder: "z. B. Pascal",
  levelLabel: "Schwierigkeit",
  levelHints: [
    "Langsamer Ball, breiter Schläger.",
    "Normales Tempo.",
    "Der Ball startet schon schnell und wird rasch schneller, der Schläger ist schmaler.",
  ],
  host: "Spiel eröffnen", orJoin: "oder beitreten", join: "Los", codePlaceholder: "code", codeLabel: "Spielcode",
  solo: "Allein gegen den Computer",
  helpServeLabel: "Aufschlag:",
  helpServe: "Einmal tippen wirft den Ball hoch, nochmals tippen schlägt. Am besten, wenn der Ring am kleinsten ist. Wo dein Schläger steht, bestimmt die Richtung.",
  helpSuperLabel: "Super-Schlag:",
  helpSuper: "Zweimal pro Ballwechsel. Tippe auf «Super» unten rechts oder wische schnell senkrecht nach oben. Der nächste Schlag fliegt schneller und tiefer, mit der Schlägerkante getroffen aber leicht ins Aus.",
  helpPcLabel: "Am PC:",
  helpPc: "Maus oder Pfeiltasten bewegen den Schläger, Klick oder Leertaste schlägt auf, Pfeil nach oben oder S lädt den Super-Schlag.",
  connecting: "Verbinde …",
  needClaude: "Zu zweit spielen klappt nur, wenn du die Seite angemeldet auf claude.ai öffnest. Gegen den Computer geht es immer.",
  codeFormat: "Der Code hat 4 Zeichen.",
  joinFailed: "Beitreten hat nicht geklappt. Versuch es nochmals.",
  waitingText: "Öffne diese Seite auf dem zweiten Handy und gib dort den Code ein. Sobald beide drin sind, geht es los.",
  share: "Link teilen", shareCopied: "Link kopiert", shareText: "Spiel Netzroller mit mir",
  cancel: "Abbrechen", again: "Revanche", back: "Zurück zum Start",
  fullscreen: "Vollbild", windowed: "Fenster", giveUp: "Aufgeben",
  turnPhone: "Handy hochkant halten", turnPhoneText: "Netzroller spielt man im Hochformat.",
  superBtn: "Super",
  you: "Du", opponent: "Gegner", computer: "Computer",

  // Spielverlauf
  start: "Spiel beginnt",
  status: (lv, games) => `${lv} · Kurzsatz bis ${games} Spiele`,
  deuce: "Einstand", adv: who => `Vorteil ${who}`, advYou: "Vorteil du",
  gameYou: "Spiel für dich", gameOpp: who => `Spiel ${who}`,
  setYou: "Satz für dich", setOpp: who => `Satz ${who}`,
  won: "Gewonnen", lost: "Verloren",
  overText: (me, op, who, lv) => `Satz ${me} : ${op} gegen ${who} · ${lv}`,
  oppGone: "Gegner ist weg · warte auf Rückkehr",
  out: "Aus!", net: "Netz!", netcord: "Netzroller!", let: "Let",
  fault: "Fehler", doubleFault: "Doppelfehler", ace: "Ass!",
  superShot: "Super-Schlag",
  serve1: "1. Aufschlag", serve2: "2. Aufschlag",
  hintServe: "Tippen: Ball hochwerfen",
  hintToss: "Nochmals tippen, wenn der Ring am kleinsten ist",
  hintOppServe: who => `${who} schlägt auf`,
  hintWait: "Warte auf Gegner",
  sideDeuce: "Einstand-Seite", sideAd: "Vorteil-Seite",

  // Direktverbindung
  p2pLoadFailed: "PeerJS konnte nicht geladen werden. Bist du online?",
  p2pNoBroker: "Keine Verbindung zum Vermittlungsserver.",
  p2pIdTaken: "Diesen Code gibt es schon. Eröffne nochmals ein Spiel.",
  p2pNotFound: "Kein offenes Spiel mit diesem Code gefunden.",
  p2pNoAnswer: "Das andere Handy antwortet nicht. Seid ihr im selben WLAN?",
  p2pFailed: type => `Verbindung fehlgeschlagen (${type || "unbekannt"}).`,
};
