// Alle Texte des Spiels. Schweizer Schreibweise: «ss», nie «ß».
// Im HTML tragen Elemente data-t="schlüssel"; main.js setzt beim Start den Text von hier ein.

export const T = {
  brandA: "Netz", brandB: "roller",
  lede: "Tennis für zwei Handys. Beide sehen den ganzen Platz, jedes Handy steuert den eigenen Schläger.",
  nameLabel: "Dein Name", namePlaceholder: "z. B. Pascal",
  levelLabel: "Schwierigkeit",
  levelHints: [
    "Langsamer Ball, breiter Schläger.",
    "Normales Tempo.",
    "Der Ball startet schon schnell und wird rasch schneller, der Schläger ist schmaler.",
  ],
  host: "Spiel eröffnen", orJoin: "oder beitreten", join: "Los", codePlaceholder: "code", codeLabel: "Spielcode",
  solo: "Allein gegen den Computer",
  helpServeLabel: "Aufschlag:",
  helpServe: "Einmal tippen wirft den Ball hoch, nochmals tippen schlägt. Am besten, wenn der Ring am kleinsten ist. Wo dein Schläger steht, bestimmt die Richtung.",
  helpSuperLabel: "Super-Schlag:",
  helpSuper: "Zweimal pro Ballwechsel. Tippe auf «Super» unten rechts oder wische schnell senkrecht nach oben. Der nächste Schlag fliegt schneller und tiefer, mit der Schlägerkante getroffen aber leicht ins Aus.",
  helpPcLabel: "Am PC:",
  helpPc: "Maus oder Pfeiltasten bewegen den Schläger, Klick oder Leertaste schlägt auf, Pfeil nach oben oder S lädt den Super-Schlag.",
  connecting: "Verbinde …",
  needClaude: "Zu zweit spielen klappt nur, wenn du die Seite angemeldet auf claude.ai öffnest. Gegen den Computer geht es immer.",
  codeFormat: "Der Code hat 4 Zeichen.",
  joinFailed: "Beitreten hat nicht geklappt. Versuch es nochmals.",
  waitingText: "Öffne diese Seite auf dem zweiten Handy und gib dort den Code ein. Sobald beide drin sind, geht es los.",
  share: "Link teilen", shareCopied: "Link kopiert", shareText: "Spiel Netzroller mit mir",
  cancel: "Abbrechen", again: "Revanche", backMenu: "Zurück zum Menü",
  fullscreen: "Vollbild", windowed: "Fenster", giveUp: "Aufgeben",
  turnPhone: "Handy hochkant halten", turnPhoneText: "Netzroller spielt man im Hochformat.",
  superBtn: "Super",
  you: "Du", opponent: "Gegner", computer: "Computer",

  // Hauptmenü
  hello: name => `Hallo, ${name}`, helloAnon: "Hallo! Deinen Namen setzt du in den Einstellungen.",
  modeQuick: "Schnelles Spiel", modeQuickSub: "Kurzsatz gegen den Computer",
  modeDuo: "Zu zweit", modeDuoSub: "Zwei Handys, ein Code",
  modeMachine: "Ballmaschine", modeCareer: "Karriere", modeDuoTour: "Turnier zu zweit", modeRanking: "Rangliste",
  soon: "bald",
  settings: "Einstellungen", introWatch: "Intro ansehen", back: "Zurück",
  duoTitle: "Zu zweit",

  modeMachineSub: "Endlos, mit Highscore", modeRankingSub: "Deine Top 10",

  // Ballmaschine
  machine: "Ballmaschine", machineStart: "Ballmaschine läuft",
  machineStatus: (lv, n) => `Ballmaschine · ${lv} · ${n} Rückschläge`,
  mPoints: "Punkte", mCombo: "Kombo", mLives: "Leben", mSpeed: "km/h",
  livesAria: (n, m) => `${n} von ${m} Leben`,
  targetHit: n => `Ziel! +${n}`, comboUp: m => `Kombo ×${m}`,
  lifeLost: n => (n === 1 ? "Noch 1 Leben" : `Noch ${n} Leben`),
  runOver: "Durchgang vorbei", newRecord: "Neuer Rekord!", againMachine: "Nochmal",
  runText: (p, c, k) => `${p} Punkte · beste Kombo ${c} · bis ${k} km/h`,
  ranking: "Rangliste", rankingSub: "Ballmaschine · deine Top 10 auf diesem Gerät",
  rankingEmpty: "Noch keine Einträge. Spiel eine Runde gegen die Ballmaschine.",
  rankingWorld: "Die Weltrangliste mit Familie und Freunden kommt in einer späteren Version.",
  rankPoints: n => `${n} P.`, rankKmh: k => `${k} km/h`,

  // Einstellungen
  profile: "Profil", landLabel: "Land",
  setSound: "Ton", setVoice: "Schiedsrichter-Stimme", setVibration: "Vibration",
  setLefty: "Linkshänder (Super-Knopf links)", setSwipe: "Super-Schlag per Wischen", setIntro: "Intro beim Start (höchstens einmal pro Tag)",
  transfer: "Profil mitnehmen", transferHelp: "Mit dem Code nimmst du Name, Land und Einstellungen auf ein anderes Gerät mit.",
  exportBtn: "Code anzeigen", copy: "Kopieren", copied: "Code kopiert.", copyManual: "Kopieren ging nicht. Der Code ist markiert, kopiere ihn von Hand.",
  importPlaceholder: "Code hier einfügen", importBtn: "Profil laden",
  imported: "Profil geladen.", importBad: "Dieser Code passt nicht. Er beginnt mit «NR1.».",
  noVoice: "Auf diesem Gerät gibt es keine deutsche Stimme. Die Rufe erscheinen nur als Banner.",

  // Intro
  introTap: "Antippen", introSkip: "Überspringen",

  // Match-Intro
  vs: "gegen", quickEvent: lv => `Schnelles Spiel · ${lv}`, duoEvent: lv => `Zu zweit · ${lv}`,
  firstServe: (who, you) => (you ? "Du schlägst auf" : `${who} schlägt auf`), tapSkip: "Antippen zum Überspringen",

  // Hawk-Eye
  hawk: "Hawk-Eye", hawkIn: "IN", hawkOut: "AUS",

  // Schiedsrichter (gesprochen)
  sayOut: "Aus!", sayNet: "Netz!", sayLet: "Let", sayFault: "Fehler", sayDoubleFault: "Doppelfehler",
  sayDeuce: "Einstand", sayAdv: who => `Vorteil ${who}`,
  sayGame: who => `Spiel ${who}`, sayMatch: who => `Spiel, Satz und Sieg ${who}`,
  sayNumbers: ["null", "fünfzehn", "dreissig", "vierzig"],
  sayAll: n => `${n} beide`,

  // Spielverlauf
  start: "Spiel beginnt",
  status: (lv, games) => `${lv} · Kurzsatz bis ${games} Spiele`,
  deuce: "Einstand", adv: who => `Vorteil ${who}`, advYou: "Vorteil du",
  gameYou: "Spiel für dich", gameOpp: who => `Spiel ${who}`,
  setYou: "Satz für dich", setOpp: who => `Satz ${who}`,
  won: "Gewonnen", lost: "Verloren",
  overText: (me, op, who, lv) => `Satz ${me} : ${op} gegen ${who} · ${lv}`,
  out: "Aus!", net: "Netz!", netcord: "Netzroller!", let: "Let",
  fault: "Fehler", doubleFault: "Doppelfehler", ace: "Ass!",
  superShot: "Super-Schlag",
  serve1: "1. Aufschlag", serve2: "2. Aufschlag",
  hintServe: "Tippen: Ball hochwerfen",
  hintToss: "Nochmals tippen, wenn der Ring am kleinsten ist",
  hintOppServe: who => `${who} schlägt auf`,
  hintWait: "Warte auf Gegner",
  sideDeuce: "Einstand-Seite", sideAd: "Vorteil-Seite",

  // Karriere (Phase 5)
  modeCareerSub: "Tour mit 63 Gegnern",
  tournaments: ["Aargau Open", "Reuss Cup", "Seetal Indoor", "Alpen Classic", "Rhein Masters", "Limmat Trophy", "Grand Slam Netzroller", "Saisonfinale"],
  categories: { "250": "Kategorie 250", "500": "Kategorie 500", "1000": "Masters 1000", GS: "Grand Slam", final: "Saisonfinale" },
  surfaceNames: { hard: "Hartplatz", clay: "Sand", clay2: "Sand", indoor: "Halle", grass: "Rasen" },
  surfaceHints: { hard: "normales Tempo", clay: "Ball langsamer, längere Ballwechsel", clay2: "langsamer, mehr Effekt", indoor: "schnell, wenig Netzroller", grass: "schnell, mehr Netzroller" },
  rounds: { R32: "1. Runde", R16: "Achtelfinal", QF: "Viertelfinal", SF: "Halbfinal", F: "Final", G: "Gruppenspiel", W: "Turniersieg", "-": "nicht gespielt" },
  groupDay: n => `Gruppenspiel ${n}`,
  styles: { wall: "Wand", cannon: "Kanone", angle: "Winkelspieler", counter: "Konterspieler", allround: "Allrounder" },
  styleHints: {
    wall: "breiter Schläger, macht fast keine Fehler", cannon: "viele Super-Schläge, harter Aufschlag, aber mehr Fehler",
    angle: "spielt scharf an die Linien", counter: "nimmt dein Tempo auf und spielt es schneller zurück", allround: "ausgeglichen",
  },
  career: "Karriere", season: n => `Saison ${n}`, rankLine: (r, p) => `Rang ${r} · ${p} Punkte`,
  careerIntro: "Du startest auf Rang 64. Spiel Turniere, sammle Ranglistenpunkte und arbeite dich nach oben. Es zählen die Punkte der letzten 8 Turniere.",
  nextTournament: "Nächstes Turnier", drawSize: n => `${n} Spieler`, formatEarly: "Kurzsatz bis 3, ab Halbfinal bis 4",
  formatGs: "Kurzsatz bis 3, ab Halbfinal bis 4, Final über zwei Gewinnsätze", formatFinal: "zwei Vierergruppen, dann Halbfinal und Final",
  playTournament: "Turnier starten", skipTournament: "Auslassen", useWildcard: "Mit Wildcard spielen",
  needRank: (need, rank) => `Für dieses Turnier brauchst du Rang ${need} oder besser (du bist ${rank}).`,
  wildcardLeft: "Du hast diese Saison noch eine Wildcard.", wildcardGone: "Deine Wildcard für diese Saison ist schon weg.",
  finalOnlyTop8: rank => `Nur die Top 8 spielen das Saisonfinale (du bist Rang ${rank}).`,
  watchTournament: "Ergebnisse ansehen", seasonPlan: "Saison", tourRanking: "Tour-Rangliste", cabinet: "Vitrine und Statistik",
  bracket: "Turnierbaum", playMatch: "Match spielen", nextMatch: (round, who) => `${round} gegen ${who}`,
  oppInfo: (rank, style) => `Rang ${rank} · ${style}`, finishTournament: "Turnier zu Ende spielen", closeTournament: "Weiter",
  youOut: round => `Ausgeschieden: ${round}`, youWatch: "Du spielst hier nicht mit.", champion: who => `Sieger: ${who}`,
  summary: (pts, a, b) => `+${pts} Punkte · Rang ${a} → ${b}`,
  groupTable: g => `Gruppe ${g}`, groupWins: n => `${n} Siege`,
  matchWon: "Sieg!", matchLost: "Niederlage", matchWonText: (round, who) => `${round} gewonnen gegen ${who}`,
  matchLostText: (round, who) => `${round} verloren gegen ${who}`, continueBtn: "Weiter",
  setWon: who => `Satz ${who}`, setWonYou: "Satz für dich", setsLine: (a, b) => `Sätze ${a}:${b}`, saySet: who => `Satz ${who}`,
  ceremony: "Siegerehrung", ceremonyText: (t, s) => `Du gewinnst ${t} in Saison ${s}.`,
  stats: { wins: "Siege", losses: "Niederlagen", aces: "Asse", doubleFaults: "Doppelfehler", longestRally: "Längster Ballwechsel", bestRank: "Beste Rangierung", titles: "Titel" },
  trophiesEmpty: "Noch keine Pokale. Gewinne ein Turnier!", trophyLine: (t, s) => `${t} · Saison ${s}`,
  racketColors: "Schlägerfarbe", colorNames: { classic: "Klassik", red: "Rot", blue: "Blau", gold: "Gold", violet: "Violett", white: "Weiss" },
  colorNeed: { wins: n => `ab ${n} Siegen`, titles: n => (n === 1 ? "ab dem ersten Titel" : `ab ${n} Titeln`), rank: n => `ab Rang ${n}` },
  newColor: name => `Neue Schlägerfarbe: ${name}`,
  newCareer: "Neue Karriere starten", newCareerConfirm: "Wirklich? Alles in der Karriere wird gelöscht. Nochmals tippen zum Bestätigen.",
  rankUp: n => `↑${n}`, rankDown: n => `↓${n}`, rankSame: "=",

  // Turnier zu zweit (Phase 6)
  modeDuoTourSub: "Gemeinsam im selben Turnier",
  duoTourName: "Turnier zu zweit", duoTourTitle: "Turnier zu zweit", duoTourHost: "Turnier eröffnen",
  duoTourHelp: "Ihr kommt ins selbe Turnierfeld, in verschiedene Hälften. Jeder spielt gleichzeitig gegen seinen Computergegner. Kommt ihr beide in den Final, spielt ihr gegeneinander.",
  duoWaitHost: "Warte auf das Turnierfeld …",
  duoYourMatch: (round, who) => `Dein ${round}: gegen ${who}`,
  duoWaitOther: who => `Warte, bis ${who} fertig gespielt hat …`,
  duoOtherLive: (who, round, a, b, opp) => `${who} spielt ${round} gegen ${opp}: ${a}:${b}`,
  duoOtherDone: (who, won) => (won ? `${who} hat gewonnen` : `${who} ist ausgeschieden`),
  duoOut: "Du bist ausgeschieden. Du kannst weiter zuschauen und anfeuern.",
  duoCheer: "Anfeuern", duoCheered: who => `${who} feuert dich an!`, duoCheerSent: "Angefeuert!",
  duoFinalReady: who => `Final gegen ${who}: Bereit`, duoFinalWait: who => `Warte, bis ${who} bereit ist …`,
  duoFinalEvent: "Turnier zu zweit · Final",
  duoClose: "Turnier abschliessen", duoLeave: "Turnier verlassen",
  duoRecorded: (pts, a, b) => `In deiner Karriere eingetragen: +${pts} Punkte · Rang ${a} → ${b}`,
  duoNotRecorded: "Weil in deiner Karriere gerade ein Turnier läuft, zählt dieses Turnier nicht für die Rangliste.",
  duoChampion: who => `Sieger: ${who}`,

  // Weltrangliste (Phase 6)
  rankLocal: "Auf diesem Gerät", rankWorld: "Weltrangliste", worldCareer: "Karriere", worldMachine: "Ballmaschine",
  worldLoading: "Lade Weltrangliste …",
  worldOff: "Die Weltrangliste ist noch nicht eingerichtet. Die Anleitung steht in der README unter «Weltrangliste einrichten».",
  worldError: "Die Weltrangliste ist gerade nicht erreichbar. Deine Ergebnisse werden später nachgeschickt.",
  worldEmpty: "Noch niemand eingetragen.",
  worldOptOut: "Du erscheinst nicht in der Weltrangliste (Einstellungen).",
  worldNoName: "Setz in den Einstellungen deinen Namen, dann erscheinst du hier.",
  worldPending: n => (n === 1 ? "1 Ergebnis wartet noch aufs Hochladen." : `${n} Ergebnisse warten noch aufs Hochladen.`),
  worldTitles: n => (n === 1 ? "1 Titel" : `${n} Titel`), worldBest: r => `beste Rangierung ${r}`,
  setOnline: "In der Weltrangliste erscheinen (nur Name und Land)",

  // Verbindung (Phase 4)
  netPaused: "Verbindung unterbrochen", netWaiting: who => `Warte auf ${who} …`,
  netHint: "Klappt es nicht? Wechselt beide ins selbe WLAN. Das Spiel geht danach mit demselben Spielstand weiter.",
  replay: "Punkt wird wiederholt", resumed: "Weiter geht's", resume: code => `Spiel ${code} fortsetzen`,

  // Direktverbindung
  p2pLoadFailed: "PeerJS konnte nicht geladen werden. Bist du online?",
  p2pNoBroker: "Keine Verbindung zum Vermittlungsserver.",
  p2pIdTaken: "Diesen Code gibt es schon. Eröffne nochmals ein Spiel.",
  p2pNotFound: "Kein offenes Spiel mit diesem Code gefunden.",
  p2pNoAnswer: "Das andere Handy antwortet nicht. Seid ihr im selben WLAN?",
  p2pFailed: type => `Verbindung fehlgeschlagen (${type || "unbekannt"}).`,
};
